- name: nginx install and run
  hosts: frontend
  become : true
  tasks:
  - name : install ngnix server
    ansible.builtin.package:
      name: nginx
      state : present

  - name : run ansible server 
    ansible.builtin.service:
      name : nginx
      state : started
      enabled : yes
